# Generated by Django 3.0.2 on 2020-02-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('other_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True)),
                ('home_country', models.CharField(blank=True, help_text='Enter home County', max_length=20, null=True)),
                ('home_county', models.CharField(blank=True, help_text='Enter home County', max_length=20, null=True)),
                ('home_town', models.CharField(blank=True, help_text='Enter home Town', max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=10, null=True)),
                ('father_first_name', models.CharField(blank=True, help_text="Enter the first name of the child's male guardian", max_length=20, null=True)),
                ('father_surname', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_first_name', models.CharField(blank=True, help_text="Enter the first name of the child's female guardian", max_length=20)),
                ('mother_surname', models.CharField(blank=True, max_length=20)),
                ('time_found', models.DateTimeField()),
                ('county_found', models.CharField(blank=True, max_length=20, null=True)),
                ('city_found', models.CharField(blank=True, max_length=20, null=True)),
                ('district_found', models.CharField(blank=True, max_length=20, null=True)),
                ('place_found', models.CharField(blank=True, max_length=40, null=True)),
                ('photo', models.ImageField(upload_to='found')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LostChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('other_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True)),
                ('home_country', models.CharField(blank=True, help_text='Enter home County', max_length=20, null=True)),
                ('home_county', models.CharField(blank=True, help_text='Enter home County', max_length=20, null=True)),
                ('home_town', models.CharField(blank=True, help_text='Enter home Town', max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=10, null=True)),
                ('father_alive', models.BooleanField(blank=True, default=True, help_text='Is the father alive?')),
                ('mother_alive', models.BooleanField(blank=True, default=True, help_text='Is the mother alive?')),
                ('father_first_name', models.CharField(blank=True, help_text="Enter the first name of the child's male guardian", max_length=20)),
                ('father_surname', models.CharField(blank=True, max_length=20, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_phone', models.IntegerField(blank=True, null=True)),
                ('mother_first_name', models.CharField(blank=True, help_text="Enter the first name of the child's female guardian", max_length=20)),
                ('mother_surname', models.CharField(blank=True, max_length=20)),
                ('mother_email', models.EmailField(max_length=254, null=True)),
                ('mother_phone', models.IntegerField(null=True)),
                ('time_last_seen', models.DateTimeField()),
                ('place_last_seen', models.CharField(blank=True, max_length=40)),
                ('county_last_seen', models.CharField(blank=True, max_length=20, null=True)),
                ('city_last_seen', models.CharField(blank=True, max_length=20, null=True)),
                ('district_last_seen', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(upload_to='lost')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['surname', 'first_name'],
            },
        ),
    ]
